# Generated by Django 5.1.4 on 2024-12-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('real_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('coffee_score', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('pwd', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(default='#b8b8b8', max_length=7)),
                ('price', models.FloatField(default=0)),
                ('scoops', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shareme.sponsor')),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='user42',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareme.user42'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoops', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('paid', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('is_order', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareme.product')),
                ('user42', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareme.user42')),
            ],
        ),
    ]
