# Generated by Django 5.1.4 on 2024-12-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user42',
            name='icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
